services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: broker-simulator
    ports:
      - "1883:1883"
      - "8083:8083"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
